# Generated by Django 2.2.16 on 2021-11-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20211117_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код подтверждения'),
        ),
    ]
