# Generated by Django 2.2.16 on 2021-11-21 13:34

from django.db import migrations, models
import reviews.models.review


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20211118_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[reviews.models.review.check_score], verbose_name='Оценка'),
        ),
    ]
