# Generated by Django 2.2.16 on 2021-11-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
