# Generated by Django 2.2.16 on 2021-11-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20211119_0551'),
        ('reviews', '0007_auto_20211121_1334'),
    ]

    operations = [
    ]
